matrix:
  include:
    - os: linux
      language: node_js
      node_js:
        - "7"
    - os: osx
      language: node_js
      node_js:
        - "7"

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      apt-get -qq update; 
      sudo apt-get install -y jq icnsutils graphicsmagick;
    fi
  - | 
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then 
      brew update; 
      brew install jq;
    fi
  
install:
  - BUCKET="https://s3.amazonaws.com/webrecorder-builds"
  - CURRENT_BRANCH="$BUCKET/$TRAVIS_BRANCH/webrecorder-player-$TRAVIS_OS_NAME"
  - DEVELOP_BRANCH="$BUCKET/develop/webrecorder-player-$TRAVIS_OS_NAME"
  - |
    if curl -o /dev/null -s -I -f "$CURRENT_BRANCH"; then
          curl -o python-binaries/webrecorder $CURRENT_BRANCH;
    else
          curl -o python-binaries/webrecorder $DEVELOP_BRANCH;
    fi
  - chmod +x python-binaries/webrecorder
  - npm install

script:
  - npm run dist
