matrix:
  include:
    - os: linux
      language: node_js
      node_js:
        - "7"
    - os: osx
      language: node_js
      node_js:
        - "7"

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      apt-get -qq update; 
      sudo apt-get install -y jq icnsutils graphicsmagick;
      PLAYER_ARTIFACT="webrecorder-player-linux"      
    fi
  - | 
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then 
      brew update; 
      brew install jq;
      PLAYER_ARTIFACT="webrecorder-player-osx"      
    fi
  
install:
  - BUCKET="https://s3.amazonaws.com/webrecorder-builds"
  - |
    if [[ $TRAVIS_BRANCH == 'master' ]]; then
      curl -o python-binaries/webrecorder $BUCKET/master/$PLAYER_ARTIFACT;
    else
      curl -o python-binaries/webrecorder $BUCKET/develop/$PLAYER_ARTIFACT;      
    fi
  - npm install

script:
  - npm run dist
