environment:
  nodejs_version: "7"
  matrix:
    - platform: x32
      ARCH_SUFFIX: '-x86'
      ARCH_ARG: '--ia32'

    - platform: x64
      ARCH_SUFFIX: '-x86_64'
      ARCH_ARG: '--x64'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

  - ps: |
        $bucket = "https://s3.amazonaws.com/webrecorder-builds/webrecorder-player"
        $destination = "$env:APPVEYOR_BUILD_FOLDER\python-binaries\webrecorder.exe"
        $current_branch = "$bucket/$env:APPVEYOR_REPO_BRANCH/webrecorder-player-win-$env:platform.exe"
        $develop_branch = "$bucket/develop/webrecorder-player-win-$env:platform.exe"

        $status = try { (invoke-webrequest -Uri $current_branch -Method Head).statuscode } catch {
        $_.Exception.Response.StatusCode.Value__
        }
        
        if ($status -eq "200") { 
            Write-Host "downloading webrecorder artifact: $current_branch"
            Invoke-WebRequest -Uri $current_branch -OutFile $destination

        }
        else {
            Write-Host "downloading webrecorder artifact: $develop_branch"
            Invoke-WebRequest -Uri $develop_branch -OutFile $destination
        }
  - ps: |
        $flash_plugin = "https://s3.amazonaws.com/webrecorder-builds/flashplugin/pepflashplayer.dll"
        Invoke-WebRequest -Uri $flash_plugin -OutFile "$env:APPVEYOR_BUILD_FOLDER\plugins\pepflashplayer.dll"
  - ps: "& $destination '-v'"

build_script:
  - ps: |
        if ($env:APPVEYOR_REPO_BRANCH -eq "master"){
          npm run dist -- $env:ARCH_ARG
        }
        else {
          npm run dist-no-gh -- $env:ARCH_ARG
        }
  - ps: "move dist/webrecorderplayer-electron*.exe $env:APPVEYOR_BUILD_FOLDER/"  

artifacts:
  - path: "webrecorderplayer-electron*.exe"
    name: webrecorderplayer-electron
    
deploy:
  provider: S3
  region: $(aws_s3_region)
  bucket: $(aws_s3_bucket)
  access_key_id: $(aws_access_key_id)
  secret_access_key: $(aws_secret_access_key)
  folder: electron-player/$(APPVEYOR_REPO_BRANCH)
  artifact: webrecorderplayer-electron
