environment:
  nodejs_version: "7"
  matrix:
    - platform: x32
      arch: 'ia32'

    - platform: x64
      arch: 'x64'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm set npm_config_arch %arch%
  - npm install

  - ps: |
        $bucket = "https://s3.amazonaws.com/webrecorder-builds/webrecorder-player"
        $destination = "$env:APPVEYOR_BUILD_FOLDER\python-binaries\webrecorder.exe"
        $current_branch = "$bucket/$env:APPVEYOR_REPO_BRANCH/webrecorder-player-win-$env:platform.exe"
        $master_branch = "$bucket/master/webrecorder-player-win-$env:platform.exe"

        $status = try { (invoke-webrequest -Uri $current_branch -Method Head).statuscode } catch {
        $_.Exception.Response.StatusCode.Value__
        }
        
        if ($status -eq "200") { 
            Write-Host "downloading webrecorder artifact: $current_branch"
            Invoke-WebRequest -Uri $current_branch -OutFile $destination

        }
        else {
            Write-Host "downloading webrecorder artifact: $master_branch"
            Invoke-WebRequest -Uri $master_branch -OutFile $destination
        }
  - ps: |
        $flash_plugin = "https://s3.amazonaws.com/webrecorder-builds/flashplugin/pepflashplayer.dll"
        Invoke-WebRequest -Uri $flash_plugin -OutFile "$env:APPVEYOR_BUILD_FOLDER\plugins\pepflashplayer.dll"
  - ps: "& $destination '-v'"

build_script:
  - ps: |
        if ($env:APPVEYOR_REPO_BRANCH -eq "master"){
          npm run dist $env:arch
        }
        else {
          npm run dist-no-gh $env:arch
        }
  - ps: "move dist/webrecorderplayer-electron*.exe $env:APPVEYOR_BUILD_FOLDER/"  

artifacts:
  - path: "webrecorderplayer-electron*.exe"
    name: webrecorderplayer-electron
    
deploy:
  provider: S3
  region: $(aws_s3_region)
  bucket: $(aws_s3_bucket)
  access_key_id: $(aws_access_key_id)
  secret_access_key: $(aws_secret_access_key)
  folder: electron-player/$(APPVEYOR_REPO_BRANCH)
  artifact: webrecorderplayer-electron
