environment:
  nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: |
        $bucket = "https://s3.amazonaws.com/webrecorder-builds"
        $destination = "C:\projects\webrecorderplayer-electron\python-binaries\webrecorder.exe"
        $current_branch = "$bucket/$env:APPVEYOR_REPO_BRANCH/webrecorder-player-win-x64.exe"
        $develop_branch = "$bucket/develop/webrecorder-player-win-x64.exe"

        if ((invoke-webrequest -Uri $current_branch -Method Head).statuscode -eq "200") { 
            Write-Host "downloading webrecorder artifact: $current_branch"
            Invoke-WebRequest -Uri $current_branch -OutFile $destination

        }
        else {
            Write-Host "downloading webrecorder artifact: $develop_branch"
            Invoke-WebRequest -Uri $develop_branch -OutFile $destination
        }

build_script:
  - npm run dist  

artifacts:
  - path: "dist/webrecorderplayer-electron*.exe"
